site: Schatz
title: Schatz
greetings: Hi 👋
description: >-
  Journey to One Piece
lang: en-US
# timezone:  Asia/Kolkata
repo: https://github.com/swarag-n/Schatz # site repo [optional]
data-theme: dark # default theme "dark" | "light"

author:
  name: Swarag Narayanasetty
  bio: One Piece of my coding archives
  # userpicture: 
  username: Swarag-N # general username
  github: Swarag-N # github username
  twitter: NSwarag # twitter username
  # email: your-email@email.com # email adress

# Font Settings
googlewebfonts: family=Space+Mono:wght@400;700&family=Fira+Code:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
url: "https://swarag-n.github.io" # Domain Name of host. [username].github.io for github pages
baseurl: "/Schatz" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

# local
# url: "http://localhost:4000" # 
# baseurl: "" # 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    # css_class: 'highlight'
    # line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: true
    # block:
    #   line_numbers: true
    #   start_line: 1

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  - templates/
  
compress_html:
  comments: ["<!-- ", " -->"]
  blanklines: true
  # clippings: all

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

paginate: 5

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


